[template]
name = "mlir-dialect-template"
description = "A template for an MLIR dialect with C and Rust bindings"
version = "0.1.0"
authors = ["Jared Hoberock <jaredhoberock@gmail.com>"]
ignore = [".git", "README.md"]

[placeholders]
dialect_name = { type = "string", prompt = "Name of your dialect", default = "foo" }
mlir_install_dir = { type = "string", prompt = "Install directory of MLIR" }
