[package]
name = "mlir-{{ dialect_name }}-dialect"
version = "0.1.0"
edition = "2024"
authors = ["{{ authors }}"]

[dependencies]
melior = "0.24"
mlir-sys = "0.5.0"

[lib]
name = "{{ dialect_name }}_dialect"
path = "src/lib.rs"
